import './globals.css'
import Link from 'next/link'
import styles from "./page.module.css";
import { Analytics } from '@vercel/analytics/react';

export const metadata = {
  title: 'Uber calculator',
  description: 'Generated by create next app',
}
// TODO: Add nav bar from tailwindcss https://tailwindui.com/components/application-ui/navigation/navbars
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.main}>
        <nav className='self-center m-5 bg-gray-400 dark:bg-slate-400 p-1 w-full'>
          <Link 
            href="/" 
            className='mx-2 text-2xl hover:scale-110 inline-block active:bg-red-400 active:text-white '
            >
            Home
          </Link>
          <Link 
            href="/calculator" 
            className='mx-2 text-2xl hover:scale-110 inline-block target:bg-red-500'>
            Calculator
          </Link>
        </nav>
        <div>
          {children}
        </div>
        <Analytics />
      </body>
    </html>
  )
}
